blog/urls.py
from django.urls import path
from .views import PostView, PostDetailView, PostCreateView, PostEditView, SignupView

app_name = 'blog'
urlpatterns = [
    path('', PostView.as_view(), name='posts'),
    path('<int:id>/', PostDetailView.as_view(), name='posts-detail'),
    path('create/', PostCreateView.as_view(), name='posts-create'),
    path('edit/<int:id>/', PostEditView.as_view(), name='posts-edit'),
    path('accounts/signup/', SignupView.as_view(), name='signup'),
]

testfinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=240)
    author = models.CharField(max_length=240, db_index=True)
    body = models.TextField()

    published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

blog/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'author', 'body', 'published']


class UserSignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def save(self):
        user = super(UserSignupForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, TemplateView
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from .forms import PostForm, UserSignupForm
from .models import Post


class PostView(View):
    def get(self, request):
        posts = Post.objects.all()
        response = [
            "{id}: {title} by {author} <br>".format(id=p.id, title=p.title, author=p.author)
            for p in posts
        ]
        return HttpResponse(response)


class PostDetailView(TemplateView):
    template_name = 'blog/detail.html'
    def get(self, request, id):
        try:
            p = Post.objects.get(id=id)
        except Post.DoesNotExist:
            raise Http404()
        else:
            context = {
                'title': p.title,
                'author': p.author,
                'body': p.body
            }
            # response = """
            # {title} by {author}
            # <br>
            # ---
            # <br><br>
            # {body}
            # """.format(title=p.title, author=p.author, body=p.body)
            # return HttpResponse(response)
            return self.render_to_response(context)


class PostCreateView(TemplateView):
    template_name = 'blog/create.html'

    def get(self, request):
        form = PostForm()
        return self.render_to_response({'form': form})

    def post(self, request):
        form = PostForm(data=request.POST)
        if not form.is_valid():
            return self.render_to_response({'errors': form.errors})

        post = form.save()
        return HttpResponseRedirect(reverse('blog:posts-detail', kwargs={'id': post.id}))


class PostEditView(TemplateView):
    template_name = 'blog/edit.html'
    def get(self, request, id):
        post = get_object_or_404(Post, id=id)
        form = PostForm(instance=post)

        return self.render_to_response({'form': form, 'id': id})

    def post(self, request, id):
        post = get_object_or_404(Post, id=id)
        form = PostForm(data=request.POST, instance=post)
        if not form.is_valid():
            return self.render_to_response({'errors': form.errors})

        post = form.save()
        return HttpResponseRedirect(reverse('blog:posts-detail', kwargs={'id': post.id}))


class SignupView(TemplateView):
    template_name = 'blog/signup.html'

    def get(self, request):
        form = UserSignupForm()
        return self.render_to_response({'form': form})

    def post(self, request):
        form = UserSignupForm(data=request.POST)
        if not form.is_valid():
            return self.render_to_response({'form': form})

        user = form.save()

        return HttpResponseRedirect(reverse('blog:posts'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

templates/blog/create.html
{% extends 'base.html' %}


{% block content %}
    <form action={% url "blog:posts-create" %} method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}

{% block content %}
    {{ title }} - {{ author }}
    <br>
    ----------
    <br><br>
    {{ body }}
{% endblock %}

templates/blog/edit.html
{% extends 'base.html' %}


{% block content %}
    <form action={% url "blog:posts-edit" id=id %} method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/blog/signup.html
{% extends 'base.html' %}


{% block content %}
    <form action={% url "blog:signup" %} method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}